name: tourbillauth
description: A framework that provides building blocks for assembling Flutter apps that require user management
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore:
  firebase_auth:
  firebase_ui_auth:
  firebase_ui_oauth_google:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  google_sign_in:
  http:
  riverpod_annotation: ^3.0.3
  tourbillon:
    git:
      https://github.com/labrom/tourbillon.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  fake_cloud_firestore:
  flutter_lints: ^1.0.0
  mockito:
  riverpod_generator: ^3.0.3

flutter:
  uses-material-design: true
